version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: 'sites'
      POSTGRES_USER: 'ripper'
      POSTGRES_PASSWORD: '150403'
    volumes:
      - .:/data/postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ripper -d sites"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"
  inno-taxi-user:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy